apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/kogito-operator.openshift-operators: ''
  name: kogito-operator
  namespace: openshift-operators
spec:
  channel: 1.x
  installPlanApproval: Automatic
  name: kogito-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: kogito-operator.v1.13.0