apiVersion: app.kiegroup.org/v1beta1
kind: KogitoBuild  # Application type
metadata:
  name: decisiontable-quarkus-example  # Application name
spec:
  type: RemoteSource
  gitSource:
    uri: 'https://github.com/kamorisan/decisiontable-quarkus-example'  # Git repository containing application (uses default branch)
    #contextDir: decisiontable-quarkus-example  # Git folder location of application
  mavenMirrorURL: >-
    http://nexusrepo-sonatype-nexus-service-demo-sample.apps.cluster-g5zsb.g5zsb.sandbox1859.opentlc.com/repository/maven-public/
  enableMavenDownloadOutput: true
  disableIncremental: true
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime  # Application type
metadata:
  name: decisiontable-quarkus-example  # Application name